name: CI/CD Deploy to deploy branch

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 首先 checkout 主分支到 src/ 目录，拿到所有源码
      - name: Checkout source to src/
        uses: actions/checkout@v3
        with:
          path: src
          fetch-depth: 0
          persist-credentials: true

      # 2. 配置 git 用户信息
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. 切到一个孤儿分支 deploy，并清空工作区
      - name: Create or reset deploy branch
        run: |
          git checkout --orphan deploy
          git rm -rf .

      # 4. 把 src/ 目录下的静态文件（HTML/CSS/JS/data.json）同步到根目录
      - name: Copy static files from src/
        run: |
          rsync -av \
            --exclude='.git/' \
            --include='*/' \
            --include='*.html' \
            --include='data.json' \
            --include='css/***' \
            --include='js/***' \
            --exclude='*' \
            src/ ./
          touch .nojekyll

      # 5. 提交并强制推送到 deploy 分支
      - name: Commit & Push to deploy
        run: |
          git add .
          git commit -m "ci: deploy static site [skip ci]" || echo "No changes to commit"
          git push -f origin deploy
